image: php:7.4-cli

stages:
  - build
  - code style
  - test

before_script:
  - bash ci/docker_install.sh > /dev/null

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

build app:
  stage: build
  script:
    - composer install

phpcs:
  stage: code style
  script:
    - composer phpcs
  needs:
    - build app

phpstan:
  stage: code style
  script:
    - composer phpstan
  needs:
    - build app

phpunit:
  stage: test
  variables:
    XDEBUG: 1
    XDEBUG_MODE: coverage
  script:
    - composer phpunit
    - composer coverage-check
  artifacts:
    reports:
      cobertura: var/log/cobertura.xml
    paths:
      - var/log
    expire_in: 1 week
  needs:
    - phpcs
    - phpstan

infection:
  stage: test
  variables:
    XDEBUG: 1
    XDEBUG_MODE: coverage
  script:
    - composer infection
  artifacts:
    paths:
      - var/log
    expire_in: 1 week
  needs:
    - phpcs
    - phpstan
