image: php:7.4-cli

stages:
  - build
  - code style
  - test

before_script:
  - apt-get update -yqq
  - apt-get install git zip -yqq
  - |
    if [[ -n ${XDEBUG} ]]; then
        pecl install xdebug
        docker-php-ext-enable xdebug
        echo "xdebug installed!"
    fi
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

build app:
  stage: build
  script:
    - composer install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/

phpcs:
  stage: code style
  script:
    - composer phpcs
  needs:
    - build app
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: pull

phpstan:
  stage: code style
  script:
    - composer phpstan
  needs:
    - build app
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: pull

phpunit:
  stage: test
  variables:
    XDEBUG: 1
    XDEBUG_MODE: coverage
  script:
    - composer phpunit
    - composer coverage-check
  coverage: '/Total code coverage is \d+\.\d+/'
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: pull
  artifacts:
    reports:
      cobertura: var/log/cobertura.xml
    paths:
      - var/log
    expire_in: 1 week
  needs:
    - phpcs
    - phpstan

infection:
  stage: test
  variables:
    XDEBUG: 1
    XDEBUG_MODE: coverage
  script:
    - composer infection
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: pull
  artifacts:
    paths:
      - var/log
    expire_in: 1 week
  needs:
    - phpcs
    - phpstan
