stages:
  - code style
  - test

before_script:
  - bash ci/docker_install.sh > /dev/null

phpcs:
  stage: code style
  image: php:7.4-cli
  script:
    - composer install
    - composer phpunit

phpstan:
  stage: code style
  image: php:7.4-cli
  script:
    - composer install
    - composer phpstan

phpunit:
  stage: test
  image: php:7.4-cli
  script:
    - composer install
    - composer phpunit
    - composer coverage-check
  variables:
    XDEBUG: 1
  needs:
    - phpcs
    - phpstan

infection:
  stage: test
  image: php:7.4-cli
  script:
    - composer install
    - composer infection
  variables:
    XDEBUG: 1
    XDEBUG_MODE: coverage
  needs:
    - phpcs
    - phpstan
