image: php:8.1-cli

stages:
  - build
  - code style
  - test
  - deploy

before_script:
  - apt-get update -yqq
  - apt-get install git zip -yqq
  - |
    if [[ -n ${XDEBUG} ]]; then
        pecl install xdebug
        docker-php-ext-enable xdebug
        echo "xdebug installed!"
    fi
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

build app:
  stage: build
  script:
    - composer install
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/

phpcs:
  stage: code style
  needs:
    - build app
  script:
    - composer phpcs
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: pull

phpstan:
  stage: code style
  needs:
    - build app
  script:
    - composer phpstan
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: pull

phpunit:
  stage: test
  needs:
    - phpcs
    - phpstan
  variables:
    XDEBUG: 1
    XDEBUG_MODE: coverage
  script:
    - composer phpunit
    - composer coverage-check
  coverage: '/Total code coverage is \d+\.\d+/'
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: pull
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: var/log/cobertura.xml
    paths:
      - var/log
    expire_in: 1 week

infection:
  stage: test
  needs:
    - phpcs
    - phpstan
  variables:
    XDEBUG: 1
    XDEBUG_MODE: coverage
  script:
    - composer infection
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - vendor/
    policy: pull
  artifacts:
    paths:
      - var/log
    expire_in: 1 week

deploy:
  stage: deploy
  needs:
    - infection
    - phpunit
  only:
    refs:
      - tags
  when: manual
  script:
    - apt-get install curl -yqq
    - 'curl --header "Job-Token: $CI_JOB_TOKEN" --data tag=${CI_COMMIT_TAG} "${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/composer"'
  environment: production
