stages:
  - code_style
  - test

before_script:
  - bash ci/docker_install.sh > /dev/null

phpcs:
  stage: code_style
  image: php:7.4-cli
  script:
    - composer install
    - composer phpunit

phpstan:
  stage: code_style
  image: php:7.4-cli
  script:
    - composer install
    - composer phpstan

phpunit:
  stage: test
  image: php:7.4-cli
  script:
    - composer install
    - composer phpunit
    - composer coverage-check

infection:
  stage: test
  image: php:7.4-cli
  script:
    - composer install
    - composer infection
